### ISSUE TITLE
'No matching state found in storage' when pressing back button after login

### ISSUE THREAD

**Issue by bogdbo** [AxaGuilDEv/react-oidc#440]
### Issue and Steps to Reproduce
1. `git clone https://github.com/AxaGuilDEv/react-oidc.git`
2. `cd react-oidc/examples/context`
3. `npm install`
4. `npm run start`
5. Open http://localhost:3000 in a browser
6. Press Login
7. Use `bob`/`bob`
8. Once logged in press `back` button once
9. This error shows up (No matching state found in storage)

![image](https://user-images.githubusercontent.com/889997/80229265-15d0e380-8648-11ea-86bd-d6067b47d273.png)

### Versions
3.0.8
#### Expected
Should not show any errors
#### Actual
shows errors
### Additional Details

- Installed packages:

**Comment by guillaume-chervet** [comment]
Hi @bogdbo,
Sorry for the delay.
Did you manage to make it works?

**Comment by bogdbo** [comment]
Hey @guillaume-chervet, sorry for the delay as well. It's been a while and I have switched a few projects since then but as far as I can recall we didn't find a solution but I think we might have switched to pure oidc.

**Comment by guillaume-chervet** [comment]
Thank you @bogdbo , I think it is a good issue to fix

**Comment by wjureczka** [comment]
I have same issue, is there any workaround @guillaume-chervet?

**Comment by guillaume-chervet** [comment]
Thank you for the solution sample, that definitively something to add.
I'am quite busy these days, I cannot tell you when I would be able to checkout this.

**Comment by wjureczka** [comment]
Hi @guillaume-chervet , I have debugged some components in order to fix this issue, but I've got stuck. Maybe you will have few minutes to help. So to start with:

We can replace this line: https://github.com/AxaGuilDEv/react-oidc/blob/master/packages/context/src/Callback/Callback.container.tsx#L9
With this: window.history.replaceState({}, window.document.title, window.location.origin + user.state.url);
and then we are properly deleting routes with `/auth/*` path from oidc-core and landing to `user.state.url`.

However, component `<OidcSecure>` is not updated and does not let its children to render, because `history.push`(ReactOidcHistory) is not called. What can I do now to help to fix bug?

**Comment by VCuzmin** [comment]
Hello! What is the status of this issue? I'm asking that because I'm quite blocked. Thank you a lot!

**Comment by guillaume-chervet** [comment]
@youf-olivier do you have time to look at this one?

**Comment by guillaume-chervet** [comment]
This behavior is fixed in v4. May i close the issue?

**Comment by bogdbo** [comment]
Thank you @guillaume-chervet
