### ISSUE TITLE
callbackComponentOverride example and redirect onSuccess

### ISSUE THREAD

**Issue by regel** [AxaGuilDEv/react-oidc#500]
### Issue and Steps to Reproduce

Hi AxaGuilDev,

I'm trying to find detailed examples of callbackComponentOverride={CallbackComponent}.

- How to customize this component and redirect the user on Success to another page (let say, the home page). I've tried react-router's useHistory and push, which does not work since the callback component itself is not inside the Router.
- How to handle errors 

Could you help me find the documentation or write a short example that achieves simple redirect on success?

Thanks for your help

Sebastien

**Comment by regel** [comment]
If I use:

```
          notAuthenticated={LoginPage}
```

and the login page is using a login 'Button':

```
import React from 'react';
import { AuthenticationContext } from '@axa-fr/react-oidc-context';

interface SimpleLoginContainerProps {
  login: any;
}

const SimpleLoginContainer: React.FC<SimpleLoginContainerProps> = (
  props: SimpleLoginContainerProps
) => {
  return (
        <button onClick={props.login}>
          Login
        </button>
  );
};

const LoginPage: React.FC = (props: any) => {
  return (
    <div>
      <AuthenticationContext.Consumer>
        {(props) => {
          return <SimpleLoginContainer login={props.login} />;
        }}
      </AuthenticationContext.Consumer>
    </div>
  );
};
```

The browser does never renders the login page. Instead, it immediately redirects to the OIDC authentication provider.

Help much appreciated.

**Comment by guillaume-chervet** [comment]
Hi @regel, very sorry for the delay. It is a very good question. I will try to provide you a working sample tomorrow.

**Comment by guillaume-chervet** [comment]
Hi @regel, I thougth about your problem,
I think the best way for the moment is to manage the redirection before you trigger the authentication.

Something like bellow 

`import React, {useEffect} from 'react';
import { withOidcUser, OidcSecure } from '@axa-fr/react-oidc-context';

const Admin = ({ oidcUser, history }) => {
    
 useEffect(() => {
    if(!oidcUser) => {
// Redirect to a page with OidcSecure
history.push("/myauthhomepage")
}
  });

    return (<><h1>Admin</h1>
    <p>Protected Admin</p>
    {oidcUser && <p>Bonjour {oidcUser.profile.name}</p></>})
};

// adding the oidc user in the props
export default withRouter(withOidcUser(Admin));`

Olivier, may be we could add a proprerty to OidcSecure in order to override auth final url behavior.

`<Secure pathCallBackOnceAuthenticated="/myhomelogged" />`

What do you think about it?

**Comment by guillaume-chervet** [comment]
Your issue is fixed in veession 4 . https://github.com/AxaGuilDEv/react-oidc/blob/master/packages/context/src/FetchUser.tsx

**Comment by guillaume-chervet** [comment]
I close the issue. It is fixed in v4. Feel free to reopen it if you need.
