### ISSUE TITLE
React router route component unmounts on history state changes when using withOidcSecure

### ISSUE THREAD

**Issue by edgaraskazlauskas** [AxaGuilDEv/react-oidc#591]
### Issue and Steps to Reproduce

React router route component unmounts on history state changes when using withOidcSecure. 
To reproduce, do a history.push call changing only the search params or history state (without changing location), take note that the given component for the route rerenders and loses all local state.

#### Expected
Component for given route does not reload (as is when not using withOidcSecure).

#### Actual
Component for given route reloads.

**Comment by rahul-sharma-uipath** [comment]
take a look at https://github.com/AxaGuilDEv/react-oidc/issues/541 - we wanted to use this library but this was a pretty big limitation so we ended up forking and using that users solution. This issue should be looked at more closely by @youf-olivier and team however and the fix is relatively straightforward so you could also just wait for the official solution.

**Comment by youf-olivier** [comment]
Yes, I have to take this one. I have some times this week. I started to take some issue. 

But this one is a bit tricky. I'll take this one soon.

**Comment by guillaume-chervet** [comment]
This is fixed by the future v4 version https://www.npmjs.com/package/@axa-fr/react-oidc-context

**Comment by guillaume-chervet** [comment]
V4 solve this issue.

**Comment by guillaume-chervet** [comment]
I close the issue fixed with v4. Feel free to reopen it if needed.
