### ISSUE TITLE
Repeated calls to openid-configuration/token in demo site

### ISSUE THREAD

**Issue by AnimaLupi** [AxaGuilDEv/react-oidc#749]
Hello, not sure if this is a real issue, so please bear with me if it isn't :-)

I was checking the demo site (https://black-rock-0dc6b0d03.1.azurestaticapps.net/) and I noticed that after I login I could see these steps repeating themselves over and over every five seconds:

### Screenshots

![image](https://user-images.githubusercontent.com/9193587/162247890-fb7aac4e-6ba7-4509-be40-c411f553304e.png)

I tried looking for 5000 ms in the codebase but I could only find a `sleep(15000)` which refers to the calls to fetch `OidcKeepAliveServiceWorker.json`.

I'm not very confident with OIDC, is that a normal thing or something's wrong?

Thank you for this cool lib by the way!

**Comment by guillaume-chervet** [comment]
Hi @AnimaLupi, thank you very much for your nice issue.

In good REST API design server is responsible to manage HTTP cache.
Theoricately, the openid-configuration can change and the client will need to have the good version.

Praticlaly we will need to add cache in javascript side :) with a configurable time cache (may be 10 minutes or one hour).
But i think we will keep the default time cache to 0.

The demo is very special because the refresh of the token is very short, in the real life it is much more longer.

**Comment by AnimaLupi** [comment]
Thank you for your quick reply!

Ok, so what I was seeing was due to a server configuration of the refresh token lifespan, I totally overlooked/missed that, sorry!

Thanks again for the explanation!

**Comment by guillaume-chervet** [comment]
I reopen the issue to trace the client cahe development need. Thank you very much :)

**Comment by guillaume-chervet** [comment]
Hi @AnimaLupi , we have added some cache in v6. Now we have less call to oidc server configuration.

**Comment by AnimaLupi** [comment]
> Hi @AnimaLupi , we have added some cache in v6. Now we have less call to oidc server configuration.

Cool, thank you for this feature!

**Comment by drue66** [comment]
Hello. In v6, if no serviceWorker is configured, the request to openid-configuration is repeated every second.

![The request to openid-configuration is repeated every second](https://user-images.githubusercontent.com/26246193/183646709-2335649c-6e7f-4ca8-ba7c-08fd280c0a46.png)

If you do not specify the serviceWorker settings in the configuration like here:

```
{
    client_id: 'interactive.public.short',
    redirect_uri: window.location.origin+'/authentication/callback',
    silent_redirect_uri: window.location.origin+'/authentication/silent-callback',
    scope: 'openid profile email api offline_access',
    authority: 'https://demo.duendesoftware.com',
    refresh_time_before_tokens_expiration_in_second: 10,
    // service_worker_relative_url:'/OidcServiceWorker.js',
    // service_worker_only: false,
  }
```

Then in the `initAsync` function, on [line 514](https://github.com/AxaGuilDEv/react-oidc/blob/a49441027dfe04dcc91ab7d6759d966d53e0896d/packages/react/src/oidc/vanilla/oidc.ts#L514), `null` will be written to the `storage` variable. But the function `fetchFromIssuer` in place of `storage` expects the type `Storage | undefined`. Because of this, the condition on [line 292](https://github.com/AxaGuilDEv/react-oidc/blob/a49441027dfe04dcc91ab7d6759d966d53e0896d/packages/react/src/oidc/vanilla/oidc.ts#L292) does not work in the `fetchFromIssuer` function.

Suggested solution:
In the `initAsync` function, on [line 514](https://github.com/AxaGuilDEv/react-oidc/blob/a49441027dfe04dcc91ab7d6759d966d53e0896d/packages/react/src/oidc/vanilla/oidc.ts#L514), replace `null` with `undefined`.

**Comment by guillaume-chervet** [comment]
Thank you @drue66 , I'am very sorry for that bug.

In fact there were 2 bugs => https://github.com/AxaGuilDEv/react-oidc/commit/06d02a920cd0845a2f151fc2bdb926d611aa3ac8
last version fixed it.

Thank you again !

**Comment by drue66** [comment]
Cool! Thank you!

**Comment by guillaume-chervet** [comment]
Hi @AnimaLupi @drue66 , i close this issue and I keep  #819 for enhancement. Thank you very much for the issue and your feedbak.
