### ISSUE TITLE
useOidcUser is null on first render

### ISSUE THREAD

**Issue by inomn** [AxaGuilDEv/react-oidc#860]
Hi! I have an issue with `useOidcUser` hook. 

### Issue and Steps to Reproduce
Login to your app.
Use  `useOidcUser` hook.
Change routes.

Code in my app:
```
const { oidcUser } = useOidcUser();
const { isAuthenticated } = useOidc();

console.log({ isAuthenticated, user: oidcUser?.name });

```

### Versions
6.5.8

### Screenshots
![Screenshot 2022-09-14 at 17 56 23](https://user-images.githubusercontent.com/6470994/190203785-a1e99fb7-202b-4235-aa07-773019d217d3.png)

#### Expected
The user should be available immediately after route change. No additional re-renders

#### Actual
User appears with some delay. The component renders 3 times. And only 3rd time with User data. If I remove `useOidcUser` and keep `useOidc` component renders only once. And `isAuthenticated` is true

**Comment by inomn** [comment]
p.s. As a workaround, I'm using `accessTokenPayload` of `useOidcAccessToken` inside of my tiny custom hook to extract user data. It contains all the data initially, without unnecessary re-renders.

```
const { accessTokenPayload } = useOidcAccessToken();
```

**Comment by guillaume-chervet** [comment]
Hi @inomn , thank you for the issue :)

useOidcUser fetch a REST service (the hook code here https://github.com/AxaGuilDEv/react-oidc/blob/master/packages/react/src/oidc/User.ts). I set it to optionnal because sometime everything is inside OidcToken or AccessToken.
I may add an option inside the configuration to preload UserInfo from REST API during callback phase in order to avoid many render.

**Comment by inomn** [comment]
Hi @guillaume-chervet and thank you for your quick ansert. Ok, now I understand, so it's pretty much expected behavior. In this case this issue can be closed. I'm fine with using `useOidcAccessToken` since I have all the data there.
