### ISSUE TITLE
Hard refresh (hard page reload) causes 401 (no serviceWorker token injection)

### ISSUE THREAD

**Issue by inomn** [AxaGuilDEv/react-oidc#861]
### Issue and Steps to Reproduce
1. Open your app (everything should work fine, serviceWorker injects headers, all good)
2. Do a hard refresh of your app (cmd+r)

### Versions
Current latest `v6.5.9`

### Screenshots
401 on hard refresh (console):
![Screenshot 2022-09-15 at 08 24 20](https://user-images.githubusercontent.com/6470994/190329736-c2c7b3ab-4115-49e5-abdb-2cd928d3dd23.png)

regular page refresh (network tab):
![Screenshot 2022-09-15 at 08 25 27](https://user-images.githubusercontent.com/6470994/190329918-8e08da36-09af-401c-b574-c643505c2fb3.png)

serviceWorker after hard refresh:
![Screenshot 2022-09-15 at 08 29 20](https://user-images.githubusercontent.com/6470994/190330656-49626f53-05d2-4793-960f-60cc7618c8fb.png)

#### Expected
Hard reload\refresh should work exactly the same way as a regular page load \ page refresh

#### Actual
Network requests fail on hard refresh

As a *temporary* workaround I'm doing a page reload in the case if the token is presented and API response is 401

**Comment by Thodor12** [comment]
Do note that this is currently how service workers are specified, a hard reload will trigger an unregistration of the service worker. So natively this is by design. I'm unsure whether we can fix this or if this is something third party devs will have to do:
https://stackoverflow.com/questions/51597231/register-service-worker-after-hard-refresh

**Comment by inomn** [comment]
Ok, thanks!
